#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

plugins=()
for plugin in $(find -maxdepth 1 -type d -regex './dotbot-.+' -printf "%f\n"); do
  plugins+=("--plugin-dir $plugin")
  echo "Enabled dotbot plugin: $plugin"
done
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" ${plugins[@]} -c "${CONFIG}" "${@}"
