{
  imports = [
    ./paths.nix
    ./user.nix
    ./neovim.nix
    ./tmux.nix
    ./starship.nix
    ./terraform.nix
    ./aws.nix
    ./gcp.nix
    ./git.nix
    ./shell.nix
    ./direnv.nix
    ./fzf.nix
    ./darwin.nix
    ./kubernetes.nix
    ./python.nix
    ./nodejs.nix
    ./golang.nix
    ./nix-tools.nix
  ];
}
