apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  set:
    logs.general.level: "INFO"
    logs.access.enabled: "true"
    ingressRoute.dashboard.entryPoints[0]: "web"
    ingressRoute.dashboard.entryPoints[1]: "traefik"
    globalArguments[0]: "--global.checknewversion=false"
    globalArguments[1]: "--global.sendanonymoususage=false"
