#!/usr/bin/zsh

# ZSH profiling
autoload -U colors && colors

# Load env
source "$HOME/dotFiles/zsh/env.zsh"

# Get funtions
source "$HOME/dotFiles/zsh/functions.zsh"

# If on WSL, load
if [[ -n "$WSL_DISTRO_NAME" ]]; then
  source "$HOME/dotFiles/wsl/wslrc.zsh"
fi

if [[ $(uname) == "Darwin" ]]; then
  source "$HOME/dotFiles/macOS/macosrc.zsh"
fi

# Set ZSH opts
source "$HOME/dotFiles/zsh/opts.zsh"

# Set ZSH zstyle
source "$HOME/dotFiles/zsh/zstyle.zsh"

# Set Keyboard
source "$HOME/dotFiles/zsh/keyboard.zsh"

# Set Local
source "$HOME/dotFiles/zsh/local.zsh"
